Added quotes in workflow - in fetch ami

diff --git a/.github/workflows/packerBuild.yml b/.github/workflows/packerBuild.yml
--- a/.github/workflows/packerBuild.yml
+++ b/.github/workflows/packerBuild.yml
@@ -141,7 +141,7 @@ jobs:
         run: |
             export LATEST_AMI_ID=$(aws ec2 describe-images \
               --executable-users self \
-              --filters Name=name,Values=${{ vars.AMI_NAME_PATTERN }} \
+              --filters "Name=name,Values=${{ vars.AMI_NAME_PATTERN }}" \
               --query 'Images | sort_by(@, &CreationDate)[-1].ImageId' \
               --output text)
               echo "LATEST_AMI_ID=${LATEST_AMI_ID}" >> $GITHUB_ENV
@@ -150,13 +150,16 @@ jobs:
       - name: Update Launch Template
         id: update_template
         run: |
+            LATEST_VERSION=$(aws ec2 describe-launch-templates \
+              --launch-template-id ${{ vars.LAUNCH_TEMPLATE_ID }} \
+              --query "LaunchTemplates[0].LatestVersionNumber" --output text)
             aws ec2 create-launch-template-version \
               --launch-template-id ${{ vars.LAUNCH_TEMPLATE_ID }} \
-              --source-version ${{ vars.LAUNCH_TEMPLATE_SOURCE_VERSION }} \
+              --source-version $LATEST_VERSION \
               --launch-template-data '{"ImageId": "'"${LATEST_AMI_ID}"'"}'
             aws ec2 modify-launch-template \
               --launch-template-id ${{ vars.LAUNCH_TEMPLATE_ID }} \
-              --default-version $(( ${{ vars.LAUNCH_TEMPLATE_SOURCE_VERSION }} + 1 ))
+              --default-version $(( LATEST_VERSION + 1 ))
 
       - name: Start Instance Refresh
         id: instance_refresh
@@ -171,17 +174,17 @@ jobs:
       - name: Wait for Instance Refresh to Complete
         id: wait_refresh
         run: |
-          STATUS="InProgress"
-          while [[ "${STATUS}" == "InProgress" ]]; do
-            STATUS=$(aws autoscaling describe-instance-refreshes \
-              --auto-scaling-group-name ${{ vars.AUTOSCALING_GROUP_NAME }} \
-              --instance-refresh-ids "${INSTANCE_REFRESH_ID}" \
-              --query "InstanceRefreshes[0].Status" \
-              --output text)
-            echo "Instance Refresh Status: ${STATUS}"
-            sleep 30
-          done
-          if [[ "${STATUS}" != "Successful" ]]; then
-            echo "Instance refresh failed with status: ${STATUS}"
-            exit 1
-          fi
+            STATUS="InProgress"
+                while [[ "${STATUS}" == "InProgress" || "${STATUS}" == "Pending" ]]; do
+                  STATUS=$(aws autoscaling describe-instance-refreshes \
+                    --auto-scaling-group-name ${{ vars.AUTOSCALING_GROUP_NAME }} \
+                    --instance-refresh-ids "${INSTANCE_REFRESH_ID}" \
+                    --query "InstanceRefreshes[0].Status" \
+                    --output text)
+                  echo "Instance Refresh Status: ${STATUS}"
+                  sleep 30
+                done
+                if [[ "${STATUS}" != "Successful" ]]; then
+                  echo "Instance refresh failed with status: ${STATUS}"
+                  exit 1
+                fi
